### ISSUE TITLE
[Question] How do you get such pretty looking diff views?

### ISSUE THREAD

**Issue by marwan38** [sindrets/dotfiles#2]
Hey @sindrets, I thought this would be an appropriate place for my question.

Your diffview, in the screenshot posted on the diffview repo, your diff looks really nice.

https://user-images.githubusercontent.com/2786478/131269942-e34100dd-cbb9-48fe-af31-6e518ce06e9e.png

This is what mine looks like:
![image](https://user-images.githubusercontent.com/32395961/144487237-8ae932ee-e891-44d8-941c-2d23ebca6c06.png)

Just  speculation, i think I might know why my colors are so off. Im using font colors for the highlights rather than bg colors. As for the diff `listchar`, i'm not so sure how you got yours to be offset on every line to match up so nicely.

Sorry to clutter your dotfiles repo, but, I just had to ask!

**EDIT:**
I think I'm going to clone your config and use it as a base for mine. I've been wanting to clean up and re-do my config anyways. It's clear that you've put a ton of work into yours!

**Comment by sindrets** [comment]
> Sorry to clutter your dotfiles repo, but, I just had to ask!

@marwan38 No worries! Since you're asking here instead of the diffview repo I can go into more detail about how I go about generating diff highlights etc.

> Just speculation, i think I might know why my colors are so off. Im using font colors for the highlights rather than bg colors.

Yes, you're right about that. I personally don't like how most themes define their diff highlights, so I have a little setup for dynamically generating diff colors based on other colors from the theme.

[The function is defined here](https://github.com/sindrets/dotfiles/blob/master/.config/nvim/lua/nvim-config/colorscheme.lua#L90-L109).

```lua
function M.generate_diff_colors()
  local bg = vim.o.bg
  local hl_bg_normal = hl.get_bg("Normal") or (bg == "dark" and "#111111" or "#eeeeee")

  local bg_normal = Color.from_hex(hl_bg_normal)

  local base_add = Color.from_hex(hl.get_fg("diffAdded") or "#b7ce42")
  local base_del = Color.from_hex(hl.get_fg("diffRemoved") or "#e84f4f")
  local base_mod = Color.from_hex(hl.get_fg("diffChanged") or "#51afef")

  local bg_add = base_add:blend(bg_normal, 0.85):mod_saturation(0.05)
  local bg_del = base_del:blend(bg_normal, 0.85):mod_saturation(0.05)
  local bg_mod = base_mod:blend(bg_normal, 0.85):mod_saturation(0.05)
  local bg_mod_text = base_mod:blend(bg_normal, 0.7):mod_saturation(0.05)

  hi("DiffAdd", { bg = bg_add:to_css(), fg = "NONE", gui = "NONE" })
  hi("DiffDelete", { bg = bg_del:to_css(), fg = "NONE", gui = "NONE" })
  hi("DiffChange", { bg = bg_mod:to_css(), fg = "NONE", gui = "NONE" })
  hi("DiffText", { bg = bg_mod_text:to_css(), fg = "NONE", gui = "NONE" })
end
```

If you're interested in incorporating this into your own config: it depends on [my `Color` class](https://github.com/sindrets/dotfiles/blob/master/.config/nvim/lua/nvim-config/common/color.lua) and my [highlight utils](https://github.com/sindrets/dotfiles/blob/master/.config/nvim/lua/nvim-config/common/hl.lua). The function works by using the foreground colors for `diffAdded`, `diffRemoved` and `diffChanged` as a base and then blends these with the background color for `Normal` as well as adjusting saturation and lightness. These highlights are almost always defined for most themes. `diffChanged` is sometimes missing, but it's trivial to define that in the case that it is.

The following custom command is very useful for inspecting and working with highlights. On calling it, it will bring all currently defined highlights into a new buffer (depends on `norcalli/nvim-colorizer.lua` for showing the colors):

```vim
command! -bar HiShow exe 'redir=>a | silent hi | redir END | exe "e " . tempname() . "/Highlights" '
            \ . '| call setline(1, split(g:a, "\n")) | setl buftype=nofile | ColorizerAttachToBuffer'
```

![image](https://user-images.githubusercontent.com/2786478/144516365-84cf8082-fd14-4221-bfe3-072773986973.png)

It doesn't show exactly how the highlight looks as opposed to `:so $VIMRUNTIME/syntax/hitest.vim`, but it's a lot faster.

> As for the diff listchar, i'm not so sure how you got yours to be offset on every line to match up so nicely.

This is gonna depend on your terminal emulator. First of all, make sure you use the proper box-drawing char and not a normal forward slash. The char I use is `╱` (code point: `U+2571`). As for the terminal, I use kitty. Kitty uses a lot of really nice rendering tricks. Among other things, it replaces all box-drawing chars with its own such that they always look nice regardless of line height, column width etc. There are other terminals that do similar things, like i.e. WezTerm.

> I think I'm going to clone your config and use it as a base for mine. I've been wanting to clean up and re-do my config anyways. It's clear that you've put a ton of work into yours!

That's very nice to hear! I will warn you though: my config is very personal. I have things set up in a way that works very well for me and my workflow, but it won't be right for everyone. But If you find parts of the config useful, that's great!

Just let me know if you have any other questions about the setup.

**Comment by marwan38** [comment]
Did not expect such a pleasantly written reply. You've taught me about a few things that I had no knowledge of.

> That's very nice to hear! I will warn you though: my config is very personal. I have things set up in a way that works very well for me and my workflow, but it won't be right for everyone. But If you find parts of the config useful, that's great!

Definitely, I will be adding my own touch to it, but overall it's nicely setup and clearly well thought out. It's a way to teach myself more about (n)vim as well. 

Thanks @sindrets, was a pleasure hearing from you.

**Comment by gekoramy** [comment]
Hi there
I'm also a fan of your diff-view style
In trying to recreate it, I can't manage to remove the highlighting from the `╱` characters
Can you suggest me anything about this?

**Comment by sindrets** [comment]
@gekoramy The highlight group you're looking for is `DiffDelete`. You can change the highlighting with the `:h :highlight` command: 

```vim
hi DiffDelete guibg=#3d2b40 guifg=NONE
```
